# -*- coding: utf-8 -*-
"""Python journal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jf2BSqjNoxvpuyWhAegIFf8CGxIbuc1g

12/12/25 - Basics of Python
"""

#First day - Pg.65 - 100
#tuple is an immutable, fixed length sequence
tup = (4,5,6,'string')
tup

tup1 = tuple('string')
tup1

nested_tuple = (4,5,6),(8,9)
nested_tuple[1]

#lists are mutable and variable length sequence
list1 = ["lists"]
list1

list1.append("dwarf")
list1

list1.insert(0,'hello')
list1

list1.pop(2)
list1

list1.remove("lists")
list1

"hello" in list1 #can also use not in

#concatenating and combining
[4,None,"foo"]+[1,2,3]

#sorting
a=[7,4,5,2]
a.sort()  #for characters use sort(key=len)
a

#slicing
seq = (3,4,5,6,7,3,1,2,4,7,8)
seq[1:5]  #seq[:5];seq[3:]

#reversing a tuple
reversed_seq = seq[::-1]
reversed_seq

#dictionary - it stores key value pairs use this instead of hashmaps?
d1 = {"a":"hello","b":[1,2,3]}
d1
#for inserting,accessing,setting same as tuple or list
#del for delete
#update for appending

#set is an unordered collection of unique elements
a={1,2,3,1,2,3}
a

a1 = {1,2,3,4}
b1 = {3,4,5,6}
#union function
a1.union(b1) #a1 | b1

#intersection
a1.intersection(b1) #a1 & b1
#refer table 3.1 page 78

#built in sequence functions

#sorted([3,2,1]) function
#reversed() function

#functions
def func():
  return "greet"
print(func())

def profile(name,age):
  print(name,age)
profile(name="Dhyan",age=21)

#for loop
fruits = ['apple','banana','mango']
for f in fruits:
  print(f,len(f))

#looping through a dictionary
student = {"name":"dhyan","age":21}
for key,value in student.items():
  print(key,":",value)

count = 1
while count <= 5:
  print(count)
  count+=1

#sum of a list using a function and loop
listt = [2,3,3,5,6]
def sum_list():
  sum = 0
  for i in listt:
    sum+=i
  return sum
print(sum_list())

#remove duplicates from a list - convert it to set
con_set = set(listt)
print(con_set)

#word counter
list_word = ["Hello","How","Are","You"]
def word_counter():
  count = 0
  for l in list_word:
    count+=1
  return count
print(word_counter())

"""EDGE QUESTIONS"""

if 0.2+0.3==0.5:
  print("true")
else:
  print("false")

print("/\\/\\/\\")

"""12/13/25 NUMPY - https://numpy.org/devdocs/user/absolute_beginners.html#"""

import numpy as np
arr = np.array(range(0,10))
arr

arr.dtype

arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
arr1

np.arange(10,30,5)   #np.arange(10,30)

np.zeros((3,4,7))   #np.ones((3,4,7)) as the name suggests

np.linspace(10,30,5)  #for float numbers

"""ADDING, REMOVING AND SORTING"""

x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y))

np.delete(x,1)

"""How to convert a 1D array into a 2D array"""

x.shape

x1 = x[np.newaxis, :]  #for column vector [:, np.newaxis]
x1.shape

"""BASIC OPERATIONS"""

a = np.random.rand(2,2)
a

b = np.array([(1,2),(3,4)])
b

#addition
c = a+b
c

#sqaure
b**2

#matrix multiplication
a@b

a<0.1

"""INDEXING, SLICING, ITERATING"""

arr[5]

arr[3:5]

#reversed
arr[::-1]

arr[::3] #first colon means beginning of the array, the second means end of the array and the number 3 is the step value

"""VSTACK, HSTACK"""

a1 = np.array([(1,2,3),(4,5,6)])
a2 = np.array([(7,8,9),(10,11,12)])

np.concatenate((a1,a2),axis=1)  #for vstack axis=0

np.vstack((a1,a2))

np.hstack((a1,a2))

"""BROADCASTING - operations on arrays of different sizes"""

x1*1.6

"""Reshaping and flattening multidimensional arrays"""

x

a1 = x.flatten()  #changes to new array wont affect the parent array
a1

a1.ravel() #opposite of flatten

"""CALCULUS / STATISTICS FUNCTIONS"""

a10 = 2*np.random.rand(1000) + 10
a10

np.mean(a10)

np.std(a10)

np.percentile(a10,80)  #80% of numbers are less than 11.62

import numpy as np

a = np.arange(10)
b = a[2:8]
b[:] = -1

print(a)

"""Sales Data Analysis
You have daily sales data for a small store for a month (30 days) stored as a list:
"""

sales = [200, 220, 250, 180, 210, 240, 230, 260, 200, 190, 220, 210, 250, 270, 300, 310, 290, 280, 260, 270, 300, 320, 310, 300, 290, 280, 270, 260, 250, 240]

#Convert this list into a NumPy array.
sales_arr = np.array(sales)
print("Sales Array:", sales_arr)

#Compute the average sales, maximum sales, and minimum sales.
print("Average sales:", np.average(sales_arr))
print("Maximum sales:", np.max(sales_arr))
print("Minimum sales:", np.min(sales_arr))

#Find the days when sales exceeded 280.
high_sales_days = sales_arr[sales_arr > 280]
print('Sales that exceeded 280:', high_sales_days)

"""Temperature Monitoring
A city records hourly temperatures in Celsius over a week (7 days × 24 hours = 168 readings) as a NumPy array called temps.
"""

#Convert the temperatures to Fahrenheit.
temps_cel = np.random.rand(168) + 30
temps_cel

temps_fah = (temps_cel - 30)*2
temps_fah

#Identify the coldest day and the hottest day based on daily averages.
print("Coldest day in fahrenheit, my arse is freezing: ",np.min(temps_fah))
print("Hottest day in fahrenheit: ",np.max(temps_fah))

#Find all hours when the temperature was below 0°C.
below = temps_fah[temps_fah<0.6]
print("Hours when the temperature was below 0°C: ",below)

"""Class Grades
You have grades for 5 students in 4 subjects as a NumPy array:
"""

grades = np.array([
 [85, 90, 78, 92],
 [70, 75, 80, 72],
 [88, 82, 91, 85],
 [60, 65, 58, 62],
 [95, 92, 88, 96]
])

#Compute each student’s average grade.
student1_average = np.average(grades[0])
print("Student 1: ",student1_average)
student2_average = np.average(grades[1])
print("Student 2: ",student2_average)
student3_average = np.average(grades[2])
print("Student 3: ",student3_average)
student4_average = np.average(grades[3])
print("Student 4: ",student4_average)

#Find the subject with the highest average score.
subject1_average = np.average(grades[:,0])
print("Subject 1: ",subject1_average)

#Identify students scoring above 90 in at least 2 subjects.
above_90_counts = np.sum(grades > 90, axis=1)
students_above_90 = np.where(above_90_counts >= 2)[0]
print("Students scoring above 90 in at least 2 subjects:", students_above_90)

"""FOCUS ON VECTORS

1) Temperature Alerts
"""

temp = np.random.rand(365,24) + 30
temp

#Identify all days where the temperature exceeded 35°C for more than 5 hours.
hot_hours = temp>30.9
hot_hours_count = np.sum(hot_hours,axis=1)
hot_days = np.where(hot_hours_count>5)[0]
hot_days

"""2) Sales Performance"""

sale = np.random.rand(12,6) + (3000-1000)
sale

#Find products whose average quarterly sales exceeded 500.
quaterly = sale/4
quaterly
product_qua = np.where(np.average(quaterly,axis=0)>500.123)[0]
product_qua

#Identify months where all products had sales above 2000.
all_products = np.all(sale>2000,axis=0)
all_products

"""3) Exam Score Analysis"""

scores = np.random.rand(10,5) + 80    #students vs subjects
scores

#Identify students who scored above 80 in all subjects.
top_students = np.where(np.all(scores > 80, axis=1))[0]
top_students

"""12/15/25 - LINEAR ALGEBRA WITH NumPy and SciPy

Dot product - same as inner product
"""

import numpy as np
np.dot([3j+0,5j+2],[2j+5,1j+2])

"""Vdot - same syntax as dot, unlike dot it flattens the array into a 1D array and then performs the operations.
Not as powerful as vecdot

Multi Dot
"""

from numpy.linalg import multi_dot
A = np.random.rand(100,100)
B = np.random.rand(100,10)
C = np.random.rand(10,100)
multi_dot([A,B,C])

"""VecDot - working with multiple arrays and when one wants to use broadcasting functions on arrays. Very similar to linalg.vecdot - for specifying explicitly that this is a linear algebra function"""

v = np.array([(0., 5., 0.), [0., 0., 10.], [0., 6., 8.]])
n = np.array([0., 0.6, 0.8])
np.vecdot(v, n)

"""Tensor dot"""

a_0 = np.array([[1, 2], [3, 4]])
b_0 = np.array([[5, 6], [7, 8]])
c_0 = np.tensordot(a_0,b_0,axes=0)
c_0

